# Partie 1

In [4]:
temp=[24.5, 25.1, 26.3, 27.0 , 25.8]

In [5]:
import numpy as np

tempNP=np.array(temp)

In [6]:
print(temp*2)
print(tempNP*2)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
[49.  50.2 52.6 54.  51.6]


On constate que l'opération de multiplication est effectuée de deux manières différentes : la liste duplique ses éléments, tandis que le ndarray multiplie chacun de ses éléments par 2.

# Partie 2 – Création des données

In [9]:
tempNP=np.zeros(10)

tempNP

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
liste1=np.ones(10)
liste1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
liste25=np.full(fill_value=25,shape=10)
liste25

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [15]:
matrice=np.eye(5)
print(matrice)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
tim=np.arange(24)
tim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
valRegu=np.linspace(20,30,10)
valRegu

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

In [21]:
np.random.seed(0)
x= np.random.uniform(15, 35, 100)
x

array([25.97627008, 29.30378733, 27.05526752, 25.89766366, 23.47309599,
       27.91788226, 23.75174423, 32.83546002, 34.27325521, 22.66883038,
       30.83450076, 25.5778984 , 26.36089122, 33.51193277, 16.42072116,
       16.74258599, 15.40436795, 31.65239691, 30.56313502, 32.40024296,
       34.57236684, 30.98317128, 24.22958725, 30.61058353, 17.36548852,
       27.79842043, 17.86706575, 33.89337834, 25.43696644, 23.2932388 ,
       20.29111224, 30.48467379, 24.12300664, 26.36867898, 15.37579601,
       27.35270994, 27.24191445, 27.33867994, 33.87496157, 28.63640598,
       22.19015801, 23.74063908, 28.95262392, 16.20450943, 28.33533431,
       28.41275739, 19.20765122, 17.57852595, 21.30856702, 22.27421542,
       26.40393541, 23.77203027, 34.76747676, 17.04089621, 19.17753512,
       18.22619036, 28.06216651, 20.06583205, 24.32621546, 19.88851184,
       18.17939167, 17.20750282, 28.12659179, 17.76365903, 18.93164723,
       22.37450341, 31.4198646 , 16.94202552, 31.75889815, 16.92

# Partie 3 – Exploration des tableaux

In [ ]:
temp=np.random.normal(30,5,24)

In [23]:
print("nombre de dimensions",temp.ndim)
print("nombre de valeurs",temp.size)
print("type des données",temp.dtype)
print("forme du tableau",temp.shape)

nombre de dimensions 1
nombre de valeurs 24
type des données float64
forme du tableau (24,)
