# Partie 1

In [4]:
temp=[24.5, 25.1, 26.3, 27.0 , 25.8]

In [5]:
import numpy as np

tempNP=np.array(temp)

In [6]:
print(temp*2)
print(tempNP*2)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
[49.  50.2 52.6 54.  51.6]


On constate que l'opération de multiplication est effectuée de deux manières différentes : la liste duplique ses éléments, tandis que le ndarray multiplie chacun de ses éléments par 2.

# Partie 2 – Création des données

In [9]:
tempNP=np.zeros(10)

tempNP

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
liste1=np.ones(10)
liste1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
liste25=np.full(fill_value=25,shape=10)
liste25

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [15]:
matrice=np.eye(5)
print(matrice)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
tim=np.arange(24)
tim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
valRegu=np.linspace(20,30,10)
valRegu

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

In [21]:
np.random.seed(0)
x= np.random.uniform(15, 35, 100)
x

array([25.97627008, 29.30378733, 27.05526752, 25.89766366, 23.47309599,
       27.91788226, 23.75174423, 32.83546002, 34.27325521, 22.66883038,
       30.83450076, 25.5778984 , 26.36089122, 33.51193277, 16.42072116,
       16.74258599, 15.40436795, 31.65239691, 30.56313502, 32.40024296,
       34.57236684, 30.98317128, 24.22958725, 30.61058353, 17.36548852,
       27.79842043, 17.86706575, 33.89337834, 25.43696644, 23.2932388 ,
       20.29111224, 30.48467379, 24.12300664, 26.36867898, 15.37579601,
       27.35270994, 27.24191445, 27.33867994, 33.87496157, 28.63640598,
       22.19015801, 23.74063908, 28.95262392, 16.20450943, 28.33533431,
       28.41275739, 19.20765122, 17.57852595, 21.30856702, 22.27421542,
       26.40393541, 23.77203027, 34.76747676, 17.04089621, 19.17753512,
       18.22619036, 28.06216651, 20.06583205, 24.32621546, 19.88851184,
       18.17939167, 17.20750282, 28.12659179, 17.76365903, 18.93164723,
       22.37450341, 31.4198646 , 16.94202552, 31.75889815, 16.92

# Partie 3 – Exploration des tableaux

In [ ]:
temp=np.random.normal(30,5,24)

In [23]:
print("nombre de dimensions",temp.ndim)
print("nombre de valeurs",temp.size)
print("type des données",temp.dtype)
print("forme du tableau",temp.shape)

nombre de dimensions 1
nombre de valeurs 24
type des données float64
forme du tableau (24,)


# Partie 4 – Indexation et slicing

In [24]:
temp[0]

np.float64(24.174250796083218)

In [25]:
temp[-1]

np.float64(34.846983540790056)

In [26]:
temp[8]

np.float64(24.646236892447288)

In [27]:
temp[8:13]

array([24.64623689, 35.27225863, 27.98411527, 36.11222535, 31.04137489])

In [28]:
temp[:7]

array([24.1742508 , 34.50413243, 32.3283122 , 22.31878157, 37.44126097,
       39.47944588, 35.89389786])

In [29]:
temp[::2]

array([24.1742508 , 32.3283122 , 37.44126097, 35.89389786, 24.64623689,
       27.98411527, 31.04137489, 31.78183199, 30.0525001 , 30.63456046,
       39.41575349, 23.64757501])

# Partie 5 – Filtrage booléen

In [30]:
temp[temp>30]

array([34.50413243, 32.3283122 , 37.44126097, 39.47944588, 35.89389786,
       35.27225863, 36.11222535, 31.04137489, 34.88319518, 31.78183199,
       33.53286584, 30.0525001 , 38.92935247, 30.63456046, 32.00994682,
       39.41575349, 34.84698354])

In [31]:
temp[(temp>20) & (temp<30)]

array([24.1742508 , 22.31878157, 29.10037582, 24.64623689, 27.98411527,
       23.26120469, 23.64757501])

In [33]:
anomalies=(temp<20) | (temp>30)
anomalies

array([False,  True,  True, False,  True,  True,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True])

In [34]:
anomalies.sum()

np.int64(17)

# Partie 6 – Manipulation des dimensions

In [36]:
data=np.random.normal(27,5,5*24).reshape((5,24))
data

array([[19.29601493, 27.31630997, 27.78253269, 28.16090518, 24.01341966,
        25.81039135, 19.87969546, 24.53340058, 24.28569262, 29.08025023,
        21.21908784, 30.90599051, 34.47242272, 16.65007487, 29.13129365,
        30.38454018, 23.81281487, 25.01364093, 26.33559711, 25.5110456 ,
        25.45493515, 18.61998097, 32.76165782, 32.39809296],
       [22.9331787 , 19.66787836, 29.60532438, 24.12106015, 27.70976582,
        25.40335791, 30.45769376, 30.47374572, 23.37201311, 20.08318022,
        19.08530801, 30.0518969 , 21.05570371, 24.46591823, 24.01842981,
        26.73716352, 17.31860097, 27.94389298, 29.61945512, 27.44211044,
        25.44556914, 27.48700083, 28.99523173, 13.13703622],
       [36.77956154, 28.95046661, 23.73795709, 25.04523312, 29.46870889,
        26.4194803 , 16.84657766, 37.32246431, 26.44729671, 32.10086356,
        23.53975076, 34.68188527, 28.43171844, 30.04421917, 21.77373317,
        33.05572645, 30.44909082, 33.50923115, 23.8595622 , 24.59486441,
  

In [37]:
data.flatten()

array([19.29601493, 27.31630997, 27.78253269, 28.16090518, 24.01341966,
       25.81039135, 19.87969546, 24.53340058, 24.28569262, 29.08025023,
       21.21908784, 30.90599051, 34.47242272, 16.65007487, 29.13129365,
       30.38454018, 23.81281487, 25.01364093, 26.33559711, 25.5110456 ,
       25.45493515, 18.61998097, 32.76165782, 32.39809296, 22.9331787 ,
       19.66787836, 29.60532438, 24.12106015, 27.70976582, 25.40335791,
       30.45769376, 30.47374572, 23.37201311, 20.08318022, 19.08530801,
       30.0518969 , 21.05570371, 24.46591823, 24.01842981, 26.73716352,
       17.31860097, 27.94389298, 29.61945512, 27.44211044, 25.44556914,
       27.48700083, 28.99523173, 13.13703622, 36.77956154, 28.95046661,
       23.73795709, 25.04523312, 29.46870889, 26.4194803 , 16.84657766,
       37.32246431, 26.44729671, 32.10086356, 23.53975076, 34.68188527,
       28.43171844, 30.04421917, 21.77373317, 33.05572645, 30.44909082,
       33.50923115, 23.8595622 , 24.59486441, 38.51958349, 21.69

In [38]:
data.T

array([[19.29601493, 22.9331787 , 36.77956154, 27.48862484, 23.40197806],
       [27.31630997, 19.66787836, 28.95046661, 29.9147684 , 22.93503506],
       [27.78253269, 29.60532438, 23.73795709, 25.00275485, 28.37258179],
       [28.16090518, 24.12106015, 25.04523312, 28.85027944, 22.54542459],
       [24.01341966, 27.70976582, 29.46870889, 20.46736574, 21.2132237 ],
       [25.81039135, 25.40335791, 26.4194803 , 35.2906534 , 25.43853874],
       [19.87969546, 30.45769376, 16.84657766, 26.40917977, 26.21166492],
       [24.53340058, 30.47374572, 37.32246431, 23.59910898, 38.28361749],
       [24.28569262, 23.37201311, 26.44729671, 30.33191541, 23.47649862],
       [29.08025023, 20.08318022, 32.10086356, 24.69640106, 31.71630362],
       [21.21908784, 19.08530801, 23.53975076, 20.32870764, 30.73594167],
       [30.90599051, 30.0518969 , 34.68188527, 20.26641247, 21.05527522],
       [34.47242272, 21.05570371, 28.43171844, 30.46886576, 30.86626489],
       [16.65007487, 24.46591823, 30.0

In [42]:
data[0,:]

array([19.29601493, 27.31630997, 27.78253269, 28.16090518, 24.01341966,
       25.81039135, 19.87969546, 24.53340058, 24.28569262, 29.08025023,
       21.21908784, 30.90599051, 34.47242272, 16.65007487, 29.13129365,
       30.38454018, 23.81281487, 25.01364093, 26.33559711, 25.5110456 ,
       25.45493515, 18.61998097, 32.76165782, 32.39809296])

In [41]:
data[4,:]

array([23.40197806, 22.93503506, 28.37258179, 22.54542459, 21.2132237 ,
       25.43853874, 26.21166492, 38.28361749, 23.47649862, 31.71630362,
       30.73594167, 21.05527522, 30.86626489, 21.0805968 , 13.70413881,
       30.03159762, 18.22054708, 29.25467231, 23.57994551, 35.29775398,
       32.342547  , 24.73307098, 23.56081194, 20.92961298])

In [43]:
data[:,11]

array([30.90599051, 30.0518969 , 34.68188527, 20.26641247, 21.05527522])

In [44]:
data[2:5,8:13]

array([[26.44729671, 32.10086356, 23.53975076, 34.68188527, 28.43171844],
       [30.33191541, 24.69640106, 20.32870764, 20.26641247, 30.46886576],
       [23.47649862, 31.71630362, 30.73594167, 21.05527522, 30.86626489]])

# Partie 7 – Concaténation

In [46]:
data2=np.random.normal(20,4,3*24).reshape((3,24))

In [54]:
merge1=np.concatenate((data,data2))
merge1.shape

(8, 24)

In [57]:
merge2=np.vstack((data,data2))
merge2.shape

(8, 24)

# Partie 8 - Calcul scientifique

In [67]:
print("minimum",data.min())
print("maximum",data.max())
print("somme",data.sum())
print("moyenne",data.mean())
print("médiane",np.median(data))
print("variance",np.var(data))
print("Ecart type",data.std())

minimum 13.137036217866749
maximum 38.51958348841971
somme 3155.537822619765
moyenne 26.296148521831373
médiane 26.265958207894656
variance 24.51870263385018
Ecart type 4.951636359209971


In [68]:
dataStandartize=(data-np.mean(data))/np.std(data)

In [72]:
dataStandartize
print(f"Moyenne : {dataStandartize.mean():.2f} et ecart type {np.std(dataStandartize)}")

Moyenne : 0.00 et ecart type 1.0


In [75]:
dataNormalize=(data-data.min())/(data.max()-data.min())
print(f" Le minimum du dataset est mtn {dataNormalize.min()} le maximum est {dataNormalize.max()}")

 Le minimum du dataset est mtn 0.0 le maximum est 1.0


In [78]:
#Formule : (°C × 9/5) + 32

temp_fahren = (data * 9/5) + 32
